module.exports.DIFFICULTIES = ["easy", "intermediate", "hard", "extremely hard"]
module.exports.TOPICS = [
    'Global Warming',
    'Renewable Energy',
    'Artificial Intelligence',
    'The Internet of Things',
    'Space Exploration',
    'Wildlife Conservation',
    'Historical Events',
    'Ancient Civilizations',
    'Cultural Diversity',
    'Human Rights',
    'Education Systems',
    'Technological Advances',
    'Urbanization',
    'Sustainable Development',
    'Medical Breakthroughs',
    'Genetic Engineering',
    'Climate Change',
    'Environmental Pollution',
    'Tourism Industry',
    'Globalization',
    'Economic Development',
    'Social Media Impact',
    'Cyber Security',
    'Renewable Resources',
    'Food Security',
    'Public Health Issues',
    'Water Scarcity',
    'Migration Patterns',
    'Workplace Diversity',
    'E-commerce Trends',
    'Digital Transformation',
    'Artificial Intelligence in Healthcare',
    'Renewable Energy Innovations',
    'Global Trade Policies',
    'Cultural Heritage',
    'Sports and Society',
    'Mental Health Awareness',
    'Biodiversity Conservation',
    'Space Colonization',
    'Blockchain Technology',
    'Future of Work',
    'Aging Population',
    'Virtual Reality',
    'Renewable Energy vs Fossil Fuels',
    'Climate Change Policies',
    'Ethical Consumerism',
    'Autonomous Vehicles',
    'Telemedicine',
    'Smart Cities',
    'Quantum Computing',
    'Cryptocurrency Regulation',
    'Antibiotic Resistance',
    'Microplastics in Oceans',
    'Bioluminescent Organisms',
    'Nanotechnology in Medicine',
    'Astrobiology',
    'Vertical Farming',
    'Synesthesia',
    'Crowdsourcing Solutions',
    'Augmented Reality in Education',
    'Zero Waste Movement',
    'Cognitive Behavioral Therapy',
    'Ethnobotany',
    'The Science of Happiness',
    'Dark Matter and Dark Energy',
    'Eco-Tourism',
    'Biohacking',
    'Sleep Disorders',
    'Asteroid Mining',
    'Renewable Energy Storage',
    'Wearable Technology',
    'Digital Nomad Lifestyle',
    'Cultural Intelligence',
    'Forensic Psychology',
    'Smart Fabrics',
    'Intermittent Fasting',
    'Philosophy of Mind',
    'Ocean Acidification',
    'The Ethics of AI',
    'Mindfulness and Meditation',
    'Cryptography',
    'Behavioral Economics',
    'The Sharing Economy',
    'Plant-Based Diets',
    'Geoengineering',
    'Mind-Body Connection',
    'The Psychology of Color',
    'Animal Cognition',
    'Hyperloop Transportation',
    'Neuroplasticity',
    'Robot Ethics',
    'Urban Green Spaces',
    'Digital Detox',
    'Epigenetics',
    'The Future of Libraries',
    'Edible Insects',
    'Space Debris',
    'The Science of Music'
];
module.exports.ESSAY_TONES = [
    'optimistic',
    'argumentative', 
    'reflective',
    'sarcastic', 
    'serious', 
    'humorous',
    'informative', 
    'persuasive',
    'critical',
    'objective', 
    'subjective',
    'ironic',
    'formal', 
    'casual',
    'passionate'
];
function chooseRandomElement(array) {
    return array[Math.floor(Math.random() * array.length)];
}
module.exports.generateRandomPresets = (diff) => {
    return [diff, chooseRandomElement(module.exports.TOPICS), chooseRandomElement(module.exports.ESSAY_TONES)]
}